[default_apps]
calendar_client = "calendar"
terminal = "ghostty"
browser = "firefox"

[units]
lengths = "meters"
weights = "kg"
volumes = "l"
temperatures = "C"
currency = "eur"

[debug]
try_suppress_errors = false
try_suppress_warnings = false
app_paths = []

[appearance]
width = 900
height = 593
gsk_renderer = "cairo"
icon_size = 22
use_base_css = true
opacity = 1.0
mod_key_ascii = ["⇧", "⇧", "⌘", "⌘", "⎇", "✦", "✦", "⌘"]

[behavior]
use_xdg_data_dir_icons = true
animate = true

[binds]
up = "control-k"
down = "control-j"
left = "control-h"
right = "control-l"
context = "control-i"
modifier = "control"
exec_inplace = "control-return"

[files]
config = "/home/hannes/.config/sherlock/config.toml"
css = "/home/hannes/.config/sherlock/main.css"
fallback = "/home/hannes/.config/sherlock/fallback.json"
alias = "/home/hannes/.config/sherlock/sherlock_alias.json"
ignore = "/home/hannes/.config/sherlock/sherlockignore"
actions = "/home/hannes/.config/sherlock/sherlock_actions.json"

[runtime]
multi = false
center = false
photo_mode = false
display_raw = false
daemonize = false

[caching]
enable = true
cache = "/home/user/.cache/sherlock/desktop_cache.bin"

[expand]
enable = false
edge = "top"
margin = 0

[backdrop]
enable = false
opacity = 0.6
edge = "top"

[status_bar]
enable = true

[search_bar_icon]
enable = true
icon = "system-search-symbolic"
icon_back = "sherlock-back"
size = 22
